"""change column def

Revision ID: fbb3c327123d
Revises: c0c105345e4e
Create Date: 2022-01-24 13:52:39.752923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbb3c327123d'
down_revision = 'c0c105345e4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('items', 'title',
               existing_type=mysql.VARCHAR(length=191),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('items', 'description',
               existing_type=mysql.VARCHAR(length=191),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('roles', 'name',
               existing_type=mysql.VARCHAR(length=191),
               type_=sa.String(length=255, collation='utf8mb4_bin'),
               existing_nullable=False)
    op.alter_column('roles', 'description',
               existing_type=mysql.VARCHAR(length=191),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('users', 'username',
               existing_type=mysql.VARCHAR(length=191),
               type_=sa.String(length=255, collation='utf8mb4_bin'),
               existing_nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=mysql.VARCHAR(length=191),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=191),
               existing_nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.String(length=255, collation='utf8mb4_bin'),
               type_=mysql.VARCHAR(length=191),
               existing_nullable=False)
    op.alter_column('roles', 'description',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=191),
               existing_nullable=True)
    op.alter_column('roles', 'name',
               existing_type=sa.String(length=255, collation='utf8mb4_bin'),
               type_=mysql.VARCHAR(length=191),
               existing_nullable=False)
    op.alter_column('items', 'description',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.VARCHAR(length=191),
               existing_nullable=True)
    op.alter_column('items', 'title',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=191),
               existing_nullable=True)
    # ### end Alembic commands ###
